name: Deploy the kaylordut debian package

on:
  workflow_run:
    workflows: ["Build the kaylordut debian package"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: kaylordut-${{ needs.build.outputs.architecture }}

      - name: sync files
        uses: burnett01/rsync-deployments@6.0.0
        with:
            switches: -avzr
            path: ./artifact/
            remote_path: ~/kaylordut/
            remote_host: ${{ secrets.HOST }}
            remote_user: ${{ secrets.USERNAME }}
            remote_key: ${{ secrets.SSH_KEY }}
            remote_port: ${{ secrets.PORT }}

      - name: Aptly release
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            aptly repo add kaylordut ~/kaylordut/
            aptly publish update  --force-overwrite  -batch -passphrase="${{ secrets.GPG_PASSPHRASE}}" kaylordut kaylordut